# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Intro to Data Analysis with Python 
author:  <a href="https://www.yuyashibuya.com">yuyashibuya</a>
logo: assets/img/logo.png
copyright: "2023"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600 
  allow_errors: true
  exclude_patterns : [_build, Thumbs.db, .DS_Store ,"**exercise.ipynb", "**_howtopip.md"]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)


#######################################################################################
# HTML-specific settings
html:
  favicon                   : assets/img/favicon.png  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : G-2XGK4LNMSB  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://github.com/iiimethodsiv/supplementary-materials"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  analytics:

  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.
#######################################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    use_jupyterbook_latex: true
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)


repository:
  url                       : https://github.com/iiimethodsiv/supplementary-materials  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : gh-pages  # Which branch of the repository should be used when creating links

#######################################################################################
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :  
   - sphinx_inline_tabs # A list of extra extensions to load by Sphinx (added to those already used by JB).
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  recursive_update          : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
